### ISSUE TITLE
Horizontal separator styling kills Firefox dead

### ISSUE THREAD

**Issue by rjgotten** [jquery/jquery-wp-content#135]
https://github.com/jquery/web-base-template/blob/master/themes/jquery/css/base.css#L186

``` css
hr.dots {
  height: 10px;
  background-color: #eee;
  background:
    radial-gradient(circle, #eee 1px, transparent 0),
    radial-gradient(circle, #ddd 1px, #eee 1px) 1px 1px;
  background:
    -webkit-radial-gradient(circle, #eee 1px, transparent 0),
    -webkit-radial-gradient(circle, #ddd 1px, #eee 1px) 1px 1px;
  background:
    -moz-radial-gradient(circle, #eee 1px, transparent 0),
    -moz-radial-gradient(circle, #ddd 1px, #eee 1px) 1px 1px;
  background:
   -o-radial-gradient(circle, #eee 1px, transparent 0),
   -o-radial-gradient(circle, #ddd 1px, #eee 1px) 1px 1px;
  background-size:3px 3px;
  border: none;
}
```

Ok confession time; which of your designers -slash- front-enders had a brainfart and decided that it would be a good idea to tax a browser which is known to have issues with gradient rendering with over 200 repeated radial gradients that involve alpha transparancy?

My desktop workstation has Firefox pinned at 100% the moment I open any of the reference documentation pages. Thank god I'm not using a laptop or, heaven forbid; a tablet, because it would probably **melt** under the stress.

Seriously; this is a huge usability problem! I warned the jQuery UI team before (over a month ago) and I'm very disappointed to not only see it not fixed, but propagated verbatim to other hosted projects because you pushed out the new site design to more of them, unaltered.
