### ISSUE TITLE
Blog: tabular horizontal minimalist style

### ISSUE THREAD

**Issue by rxaviers** [jquery/jquery-wp-content#222]
In a blog post, I use tabular data. Our current styles seems not having any tabular style. So, instead of using default browser style, I suggest the below (while we don't have an awesome one).

OBS: I don't know where is the best place to include it. (base.css? a more specific place? Perhaps, some stuff in base.css, others - like color - in specific site css)

Eg. 1:
![path3029](https://f.cloud.github.com/assets/967155/236409/1a131d4c-87e9-11e2-9724-cb09f29fe819.png)

Eg. 2:
![path4801](https://f.cloud.github.com/assets/967155/236411/24aa4f6e-87e9-11e2-9007-ae4a8e0fa745.png)

``` css
.hor-minimalist
{
    width: 90%;
    margin: 0 5%;
    border-collapse: collapse;
}
.hor-minimalist th
{
    font-family:'klavika-web','Helvetica Neue',Helvetica,Arial,Geneva,sans-serif !important;
    font-weight: 700;
    font-size: 1.2em;
    line-height: 1.2em;
    color: #B24926;
    margin: 0 0 1em;
    padding: 10px 8px;
    border-bottom: 2px solid #666;
}
.hor-minimalist td
{
    color: #666;
    padding: 9px 8px 0px 8px;
}
.hor-minimalist tbody tr:hover td
{
    color: #333;
}
```
