### ISSUE TITLE
Code styling inside of a blockquote

### ISSUE THREAD

**Issue by Mottie** [jquery/jquery-wp-content#227]
The code examples contained within a blockquote do not match the overall styling; [one example is here](http://api.jquery.com/animate/#animation-properties)

![blockquote-code](https://f.cloud.github.com/assets/136959/368039/04c25a14-a2b7-11e2-8138-3cf94dd41e13.jpg)

One proposal would be to resize and darken the code:

``` css
blockquote code {
    font: italic 23px/26px "source-code-pro", Consolas, monospace;
    color: #555;
    word-wrap: break-word;
}
```

resulting in something like this:

![blockquote-code-after](https://f.cloud.github.com/assets/136959/368077/164095a2-a2b8-11e2-8366-043fde995fde.jpg)
