### ISSUE TITLE
Use transparent background-image gradients

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery-wp-content#60]
Right now each theme has its own gradient background image, which is somewhat suboptimal because it re-creates the same gradient, which means more maintenance in case of change, and requires an image to be generated for each new theme.

Instead, lets use a transparent background-image gradient and fill in the solid color behind it with css:

``` css
html.qunitjs, .qunitjs #container {
    background: #00733c url(../i/bg-body-trans.png) no-repeat center -20px;
}
```

Or even better, instead of a transparent gradient image, replace the image with css as well (css3 background-image gradient).
